"""
Django settings for cc project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'main',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'crega.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },    
]

WSGI_APPLICATION = 'crega.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/crega/static/'

# SASS support
COMPRESS_PRECOMPILERS = (
    ('text/scss', 'sass --scss {infile} {outfile}'),
)

# Security, until we have certificates for https
#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True

# Administrators
ADMINS = (('Sean Lin', 'sean.linxs@gmail.com'),)

# Sensitive settings
with open('/etc/crega/settings.json') as s:
    settings = json.load(s)

    ALLOWED_HOSTS = settings['ALLOWED_HOSTS']

    SECRET_KEY = settings['SECRET_KEY']

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = settings['DEBUG']

    # Database
    # https://docs.djangoproject.com/en/1.8/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': settings['DBENGINE'],
            'NAME': settings['DBNAME'],
            'USER': settings['DBUSER'],
            'PASSWORD': settings['DBPASS'],
            'CONN_MAX_AGE': settings['DBCONN_MAX_AGE'],
        }
    }

    # Media host
    MEDIA_HOST = settings['MEDIA_HOST']

    # Email
    EMAIL_HOST = settings['EMAIL_HOST']
    EMAIL_PORT = settings['EMAIL_PORT']
    EMAIL_HOST_USER = settings['EMAIL_HOST_USER']
    EMAIL_HOST_PASSWORD = settings['EMAIL_HOST_PASSWORD']
    ENQUIRY_EMAIL = settings['ENQUIRY_EMAIL']
